### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by GabMar** [alairock/phpunit-atom#31]
[Enter steps to reproduce below:]
1. Download phpunit.phar and put it in C:\PHP\bin\
2. Install the plugin phpunit-atom
3. Configure the PHPUnit Executable Path: C:\PHP\bin\phpunit.phar

**Atom Version**: 1.0.2
**System**: Windows 8.1
**Thrown From**: [phpunit](https://github.com/alairock/phpunit-atom) package, v1.1.1
### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At child_process.js:1145

Error: spawn UNKNOWN
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at exports.spawn (child_process.js:977:9)
  at Object.module.exports.execPHPUnit (C:\Users\Gabriele\.atom\packages\phpunit\lib\phpunit.coffee:115:9)
  at Object.module.exports.executeTests (C:\Users\Gabriele\.atom\packages\phpunit\lib\phpunit.coffee:84:21)
  at Object.module.exports.runEditor (C:\Users\Gabriele\.atom\packages\phpunit\lib\phpunit.coffee:67:10)
  at atom-workspace.<anonymous> (C:\Users\Gabriele\.atom\packages\phpunit\lib\phpunit.coffee:44:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Gabriele\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Gabriele\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Gabriele\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Gabriele\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
  7x -9:37.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -8:53.1.0 phpunit:current (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:44.3.0 core:backspace (atom-text-editor#phpunit.execPath.editor.mini.is-focused)
     -0:42.6.0 core:save (atom-text-editor#phpunit.execPath.editor.mini.is-focused)
  2x -0:36.9.0 phpunit:current (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "phpunit": {
    "execPath": "C:\\PHP\\bin\\phpunit.phar"
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.5.0
color-picker, v2.0.11
phpunit, v1.1.1

# Dev
No dev packages
```

**Comment by mdzzohrabi** [comment]
I have same issue.
```
'phpunit' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

**Comment by SC7639** [comment]
I'm having the exact same issue and atom pointed me to this issue

```
nternal/child_process.js:298
Hide Stack Trace
Error: spawn UNKNOWN
  at exports._errnoException (util.js:837:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:351:9)
  at Object.module.exports.execPHPUnit (C:\Users\SCrossan\.atom\packages\phpunit\lib\phpunit.coffee:148:20)
  at Object.module.exports.prepareExecPHPUnit (C:\Users\SCrossan\.atom\packages\phpunit\lib\phpunit.coffee:139:14)
  at Object.module.exports.executeTests (C:\Users\SCrossan\.atom\packages\phpunit\lib\phpunit.coffee:91:10)
  at Object.module.exports.runEditor (C:\Users\SCrossan\.atom\packages\phpunit\lib\phpunit.coffee:73:10)
  at atom-workspace.<anonymous> (C:\Users\SCrossan\.atom\packages\phpunit\lib\phpunit.coffee:49:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
  at __bind (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.module.exports.SelectListView.initialize.atom.commands.add.core:confirm (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
  at __bind (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
  at HTMLDocument.__bind (C:\Users\SCrossan\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by fendy3002** [comment]
In windows, I need to set the PHPUnit Executable Path to the full path of executable.
ex: C:\xampp\php\phpunit.bat

Also, don't forget to add the extension.

**Comment by dpritula** [comment]
as well, the same issue

**Comment by ericbinek** [comment]
Just create a C:\PHP\bin\phpunit.bat file with this content:

@ECHO OFF
php "%~dp0phpunit.phar" %*
