### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by domioanna** [alairock/phpunit-atom#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11
**Thrown From**: [phpunit](https://github.com/alairock/phpunit-atom) package, v1.2.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.module.exports.execPHPUnit (/Users/domioanna/.atom/packages/phpunit/lib/phpunit.coffee:148:20)
    at Object.module.exports.prepareExecPHPUnit (/Users/domioanna/.atom/packages/phpunit/lib/phpunit.coffee:139:14)
    at Object.module.exports.executeTests (/Users/domioanna/.atom/packages/phpunit/lib/phpunit.coffee:91:10)
    at Object.module.exports.runEditor (/Users/domioanna/.atom/packages/phpunit/lib/phpunit.coffee:73:10)
    at atom-workspace.<anonymous> (/Users/domioanna/.atom/packages/phpunit/lib/phpunit.coffee:49:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:55.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:52.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:52.3.0 phpunit:current (atom-text-editor.editor)
  5x -1:09.4.0 core:backspace (atom-text-editor#phpunit.execPath.editor.mini.is-focused)
     -1:02.7.0 core:save (atom-text-editor#phpunit.execPath.editor.mini.is-focused)
     -0:58.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:54.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:54.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.3.0 phpunit:current (atom-text-editor.editor)
  2x -0:27 fuzzy-finder:toggle-file-finder (a.stack-toggle)
     -0:08.2.0 core:save (atom-text-editor#phpunit.execPath.editor.mini.is-focused)
     -0:04.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 phpunit:current (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "facebook-syntax"
    ]
  },
  "phpunit": {
    "execPath": "vendor/phpunit"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
emmet, v2.3.14
facebook-syntax, v1.0.0
gist, v0.2.8
language-blade, v0.16.0
language-stylus, v0.2.0
phpunit, v1.2.0

# Dev
No dev packages
```

**Comment by bendolan** [comment]
I had a similar issue and fixed this by changing the permissions on the phpunit file:
chmod +x phpunit

**Comment by Jagepard** [comment]
Changing the permissions helped me too
